# Generated by Django 4.2.3 on 2023-07-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_new_regm'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('uname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('ph', models.IntegerField()),
                ('file', models.FileField(upload_to='')),
                ('pin', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='new_regm',
        ),
    ]
