# Generated by Django 4.2.3 on 2023-07-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_bankmodel_delete_new_regm'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmodel',
            name='balance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
