# Generated by Django 4.2.3 on 2023-07-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0011_ministatement'),
    ]

    operations = [
        migrations.CreateModel(
            name='notificationmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='ministatement',
            old_name='stament',
            new_name='statement',
        ),
    ]
