# Generated by Django 4.2.3 on 2023-07-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0012_notificationmodels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_amount',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdraw_amount',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
