# Generated by Django 4.2.3 on 2023-07-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0013_add_amount_uid_withdraw_amount_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000)),
                ('date', models.DateField()),
            ],
        ),
    ]
