# Generated by Django 4.2.3 on 2023-08-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0017_moneymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneymodel',
            old_name='ac',
            new_name='acc',
        ),
        migrations.RenameField(
            model_name='moneymodel',
            old_name='am',
            new_name='amount',
        ),
    ]
